### ISSUE TITLE
feature: publish a Snap version of the desktop-wallet

### ISSUE THREAD

**Issue by brenopolanski** [ArkEcosystem/desktop-wallet#1649]
Snaps work across Linux on any distribution or version.

Snaps are secure. All the dependencies are isolated from the rest of system. Snaps also auto update when release a new version.

So with the snap published, the user can install it using the command:

e.g: `sudo snap install ark-desktop-wallet`

- See more info here: https://snapcraft.io
- Step by step to create a Snap: https://ubuntu.com/tutorials/snap-a-website#1-overview

**Comment by davimello28** [comment]
So, this is the state of the snap package.

- `feat/linux-snap-package` is the branch for that.
- The package is working when installed with the `--dangerous` since we don't have the signatures from snap. This version was compiled from the latest `devel` branch, so I'm just using it for testing purposes.

```
sudo snap install ark-desktop-wallet-linux-amd64-2.8.0.snap --dangerous 
```
- Created the Ubuntu One/Snapcraft account and registered `ark-desktop-wallet`, so we can publish the snap package. Everything is registered under ark domain.
- Also, I'm reading the docs for both snapcraft and debian to publish them in our own repo. 

All of this work can be considered trivial without further discussion.
