### ISSUE TITLE
Feature Request: Confidentiality through Login

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/desktop-wallet#203]
I heard it several times now. A lot of users do not want that their wallets are just visible within the desktop.

It would be great if the visibility of the content within the desktop application could be protected with a password in order to prevent other users of the computer to view the accounts.

The only thing you can do now is deleting and important accounts for every usage.

Yes, they could setup different windows logins but you know how lazy some people are.

**Comment by fileninja** [comment]
It is Not enough to set a Password to See the wallet. We need to Encrypt the Storage and decrypt it in Password. Without the Encryption someone may be able to read the Storage

**Comment by Ghosthree3** [comment]
It would be handy if the password could encrypt the passphrase/private key as well so that it could be used to confirm transactions instead of having to fetch the 12 words every time. Wallets in all the other currencies I've checked out so far have always had this as a feature, the seed is encrypted in the wallet so a more user friendly password can be used instead.

If this is somehow a security concern though I understand passing on it.

**Comment by alexbarnsley** [comment]
A part of me feels that Ledger already caters for everything in this issue now (including what you mentioned @Ghosthree3) - Hidden addresses, no need to remember the passphrase (signing transactions with the ledger), secure, etc. That being said, it's still possible to implement and seems to be requested by a few people, so won't rule this out completely.

On a slightly separate note @Ghosthree3, we are working on the BIP38 integration into the Desktop Client so you will be able to use a custom password to send Ark / make transactions, instead of using the full passphrase. BIP38 has already been included in the recent RPC that was developed.
