### ISSUE TITLE
The mouse starts sporadically glitching and clicking while the program is opened

### ISSUE THREAD

**Issue by wisefox3599** [ArkEcosystem/desktop-wallet#447]
![image](https://user-images.githubusercontent.com/28910729/33799577-cf605c1a-dd2e-11e7-86ab-2c01c105ccf2.png)

**Comment by j-a-m-l** [comment]
Could you give us more info, please?

**Comment by wisefox3599** [comment]
What are you specifically interested in?
The mouse keep randomly moving around the screen and randomly left and
right clicking while the program is running. As soon as i close the
program, everything is back fine again. Im using x64 Windows 10
professional

**Comment by CreamofXtreme** [comment]
I am having this issue as well. When I steadily scroll my mouse across the screen it'll freeze for a second and the jump to where it would keep going to. It only happens when I have the ARK wallet open.
Not sure if this might be the problem...When I open the task manager, I see there are 4 processes for ARK. Is that normal?
![ark](https://user-images.githubusercontent.com/35272436/34737638-85d2ea3a-f52b-11e7-93a0-aa0945c3ac6f.png)
