### ISSUE TITLE
Sign Message with a cold wallet

### ISSUE THREAD

**Issue by jhmblvd** [ArkEcosystem/desktop-wallet#477]
When I open up the ARK client wallet I see that I have two accounts. One account has ARK in it. But when I go to Sign and Verify Message tab it says 
This address has not received any ARK so it is not on the ARK blockchain and can not be used for signing messages.

Obviously I have received ARK so what does this mean

**Comment by j-a-m-l** [comment]
@jhmblvd which version of the desktop wallet are you using?

**Comment by jhmblvd** [comment]
ARKCLIENT-Win64-1.4.3

**Comment by Nasicus** [comment]
I can verify this on the newest master branch commit.

I also found out what the problem is (maybe @jhmblvd can verify if i'ts true for him too).

Problem is that the `PublicKey` for the account is missing.
The only way this can happen for me is,when the account has not yet **SENT** any Ark. If you only have **RECEIVED** Ark it's possible to still not have a public key (tested it on DARK-Net). As soon as I sent my first Ark, a public key was available in the desktop app.

Not sure though what the fix is @j-a-m-l .

**Comment by luciorubeens** [comment]
It's not a bug, is just a cold wallet. If your passphrase has never signed any transaction your account does not exist in the database, so to sign a message through a cold wallet we need to request the passphrase..
