### ISSUE TITLE
Fetch Epoch Time value from Network (v2 API)

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/desktop-wallet#585]
The desktop wallet does not work for the persona token. There seems to be a missing time offset. Currently you have to turn back your computer time by 1 year to send transaction.

We should really stay campatible with Ark based tokens!

**Comment by alexbarnsley** [comment]
This will likely be resolved manually in a fork for Persona, but will be resolved for Ark once v2 API is released. The problem is the epoch time is currently hard coded in the ark-js and the network value cannot be pulled from the v1 API. v2 API includes this data so will be used once available. This has already been on my list for some time (due to deployer having the epoch option) but not really an easy fix without ark-node changes. I will leave open but changing the issue title to be more generic.
